---
java_package: java-17-openjdk-devel
java_home: /usr/lib/jvm/jre-17-openjdk

# defaults file for tomcat
username: tomcat
home_dir: /opt/tomcat
default_shell: /bin/false
tomcat_version: 9.0.70
tomcat_latest: /opt/tomcat/latest
tomcat_bin_directory: /opt/tomcat/latest/bin/
tomcat_service_location: /etc/systemd/system/tomcat.service
tomcat_admin_user: tomcat
tomcat_admin_password: tomcat
tomcat_users_relative: conf/tomcat-users.xml
tomcat_manager_allow_ipregex: ".*"
tomcat_allow_context_locations:
- /opt/tomcat/latest/webapps/manager/META-INF/context.xml
- /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml

# Jfrog creds 
jfrog_user: "{{ lookup('env', 'JFROG_USERNAME') }}"
jfrog_passwd: "{{ lookup('env', 'JFROG_TOKEN') }}"

# defaults for application
deploy_version: 0.0.1-SNAPSHOT
new_version: 0.0.1-20221219.074010-10
deploy_repo: libs-snapshot/com/hello/HelloWorld
deploy_file_name: HelloWorld-{{ new_version }}.war
deploy_url: https://jfrogartifactorymk12.jfrog.io/artifactory/{{ deploy_repo }}/{{ deploy_version }}/{{ deploy_file_name }}

 