---
- name: deploy any War file
  copy:
    src: /var/lib/jenkins/workspace/Pipeline/com/hello/HelloWorld/0.0.1-SNAPSHOT/HelloWorld-0.0.1-20221219.064922-10.war
    dest: /opt/tomcat/latest/webapp
    owner: "{{ username }}"
    group: "{{ username }}"
  notify:
    - reload the daemon, enable and start the tomcat service
